[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysfo"
dynamic = ["version"]
description = "A Python package for data analysis and API interactions."
authors = [
    { name = "Sergio A. Florez-Orrego", email = "saf9215@stern.nyu.edu" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pytest",
    "pandas",
    "numpy",
    "matplotlib",
    "plotly",
    "openai",
    "fredapi",
    "country_converter",
    "joblib",
    "python-dotenv",
    "dbnomics==1.2.5",
    "tomli",
    "pyarrow",
    "yfinance==1.2.0",
    "lseg-data==2.1.1",
    "openpyxl==3.1.5",
]

# [tool.setuptools]
# include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

# [tool.setuptools.package-data]
# "pysfo.basic.geo_utils" = ["json_files/*.json"]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["experimental", "tests"]

[tool.setuptools.dynamic]
version = { attr = "pysfo.__version__" }

[tool.pytest.ini_options]
pythonpath = ["src"]
